### ISSUE TITLE
Menu selection super faint - could that be stronger? with a bg?

### ISSUE THREAD

**Issue by ewerybody** [lancewilhelm/horizon-extended#2]
I have a new favorite theme!!! :)

But browsing through the menus is causing some squinting:
> ![image](https://user-images.githubusercontent.com/218956/153428839-f2a90c39-0910-4a25-aa27-ced4f65a25c6.png)

especially via keyboard when you don't have a cursor to have somewhat more aim.
Could that be improved please 🙏
thanks so far!

**Comment by lancewilhelm** [comment]
I am so happy to hear! 

I think the reason I may have missed that is because I am working on a mac and it looks like those menus are on windows vscode. Am I seeing that right? (thanks for the screenshot)

I will spin up a windows vm here today, dust off the theming cobwebs from my brain and get to work in this. 

Thanks for raising the issue!

**Comment by lancewilhelm** [comment]
I slapped a bg in there. Let me know how it looks. I think it should suffice. I can always tweak with people's feedback.

**Comment by ewerybody** [comment]
Whow that's fast! Much better now:
![image](https://user-images.githubusercontent.com/218956/153512257-a12fce67-7581-4f95-931e-a231c56c7c10.png)

Thanks again! Great work! 🤘

**Comment by ewerybody** [comment]
oh and yeah: That was Windows!
